import 'dotenv/config';
import express from 'express';
import http from 'http';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { Server } from 'socket.io';
import { connectDB } from './config/database';
import { errorHandler } from './middleware/errorHandler';
import { authRoutes } from './routes/authRoutes';
import { animeRoutes } from './routes/animeRoutes';
import { userRoutes } from './routes/userRoutes';
import { favoriteRoutes } from './routes/favoriteRoutes';
import { historyRoutes } from './routes/historyRoutes';
import { chatRoutes } from './routes/chatRoutes';
import { downloadRoutes } from './routes/downloadRoutes';
import { musicRoutes } from './routes/musicRoutes';
import { mobileBlueprintRoutes } from './routes/mobileBlueprintRoutes';
import { postRoutes, storyRoutes, reelRoutes, profileRoutes, notificationRoutes, searchRoutes, reportRoutes, callRoutes, adminRoutes } from './routes/mobileSocialRoutes';
const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: process.env.CLIENT_URL || '*' } });
app.set('io', io);
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || '*', credentials: true }));
app.use(express.json({ limit: '2mb' }));
app.use(morgan('dev'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 200 }));
app.get('/api/health', (_req, res) => res.json({ ok: true, app: 'BoundUp API' }));
app.use('/api/auth', authRoutes);
app.use('/api/anime', animeRoutes);
app.use('/api/users', userRoutes);
app.use('/api/favorites', favoriteRoutes);
app.use('/api/history', historyRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/downloads', downloadRoutes);
app.use('/api/music', musicRoutes);
app.use('/api/mobile', mobileBlueprintRoutes);
app.use('/api/posts', postRoutes);
app.use('/api/stories', storyRoutes);
app.use('/api/reels', reelRoutes);
app.use('/api/profiles', profileRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/search', searchRoutes);
app.use('/api/reports', reportRoutes);
app.use('/api/calls', callRoutes);
app.use('/api/admin', adminRoutes);
io.on('connection', socket => {
  socket.on('room:join', roomId => socket.join(roomId));
  socket.on('typing', data => socket.to(data.roomId).emit('typing', data));
  socket.on('message:send', data => io.to(data.roomId || 'demo').emit('message:new', data));
  socket.on('call:join', data => socket.join(data.callId));
  socket.on('call:signal', data => socket.to(data.callId).emit('call:signal', data));
});
app.use(errorHandler);
const PORT = Number(process.env.PORT || 5000);
connectDB(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/boundup').then(() => server.listen(PORT, () => console.log(`BoundUp API running on ${PORT}`)));
